#!/bin/bash

video=$(find . -type f | grep 'mp4\|mkv' | fzf --prompt='Video: ' --layout=reverse)
audio=$(find . -type f | grep 'mp3\|m4a\|wav' | fzf --prompt='Audio: ' --layout=reverse)
output=$(echo $(basename $video) | cut -f 1 -d '.' | cut -f 1 -d '-')
ffmpeg -i $video -i $audio -c:v copy -c:a aac "$output.mp4"
ffplay "$output.mp4"
read -p "Delete input? [y/N] " -n 1 -r

if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm $video $audio
fi
