#!/bin/bash

if [[ $# -lt 2 ]]; then
	echo "Usage: volume video [volume-value]"
	exit 1
fi
name=$(basename --suffix=".mp4" $1)

# ffmpeg -i $1 -filter:a "volume=$2" "$2-$1"
ffmpeg -i "$name.mp4" -filter:a "volume=$2" "$name-$2.mp4"
